
CREATE TABLE SALARY (
    id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    value INTEGER NOT NULL
);


CREATE TABLE EMPLOYEE (
    id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    salaryID INTEGER,
    FOREIGN KEY (salaryID) REFERENCES salary(id)
);

